services:
  web:
    build: .
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    env_file:
      - secrets.env
    environment:
      - DEBUG=True
      - REDIS_HOST=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: [ "redis-server", "--bind", "0.0.0.0", "--port", "6379" ]


